### ISSUE TITLE
Animal types

### ISSUE THREAD

**Issue by elexis1** [0ADMods/maps_random_by_kali#10]
- On mediterranean I can barely find any deer, if at all some in the caucasus
- Walrus shouldn't be placed in scandinavia (replace with deer?)
- Polar wolves don't really fit to scandinavia either, common wolves however do, so maybe we can slip that

**Comment by ghost** [comment]
Changed to the following biome animals:

Autumn: sheep, wolves
Desert: camels, gazelles
Medit: deer, goats
Polar: muskox, wolves
Steppe: deer, horses
Temperate: pig, boar
