### ISSUE TITLE
remove maps that I don't want to work on

### ISSUE THREAD

**Issue by ghost** [0ADMods/maps_random_by_kali#14]
@elexis1 is it OK to delete Safe House, Outpost, Outward Bound and Ring from this repo? I don't have any interest in working on them further.

**Comment by niektb** [comment]
Deleting is maybe a bit too radical but moving them to an 'old and unfinished' folder is fine on my end

**Comment by ghost** [comment]
cool, moved: https://github.com/0ADMods/maps_random_by_kali/tree/master/maps/random/old
