### ISSUE TITLE
Volcano smoke on pompeii

### ISSUE THREAD

**Issue by elexis1** [0ADMods/maps_random_by_kali#16]
Few smoke clouds would add to the eyecandy. Notice that its a bit of a conflict that the volcano is just active while all the people have become skeletons already (indicating time being passed), but that should be fine. Maybe it had become active again afterwards.

**Comment by ghost** [comment]
I likely won't have time this week to update, but feel free to add smoke if you like.

**Comment by ghost** [comment]
added smoke
