### ISSUE TITLE
Dust on Red Sea

### ISSUE THREAD

**Issue by elexis1** [0ADMods/maps_random_by_kali#17]
It was suggested to add dust for red sea:
https://wildfiregames.com/forum/index.php?/topic/20975-random-maps-placement-of-thing/

Stan wrote a dust actor that fits better with regards to the color. I wrote a patch that uses it.

Please check that the amount of dust is okay, then I'll commit it:

[dust.patch.txt](https://github.com/0ADMods/maps_random_by_kali/files/375006/dust.patch.txt)

**Comment by ghost** [comment]
I love the dust! Really brings the terrain to life.

I might recommend avoiding the water classes and increasing the distance from the player's base:
avoidClasses(g_TileClasses.player, 5)
becomes:
avoidClasses(g_TileClasses.player, 10, g_TileClasses.water, 3)

Really like it!
