### ISSUE TITLE
Impassable terrain on small map sizes

### ISSUE THREAD

**Issue by ghost** [0ADMods/maps_random_by_kali#18]
@elexis1 The old algorithm was creating impassable terrain on smaller map sizes because the height was remaining constant while the distance was shrinking, creating steeper slopes. I added a line to gaia.js that scales the height by map size.
[height_scaling.diff.txt](https://github.com/0ADMods/maps_random_by_kali/files/376542/height_scaling.diff.txt)

Can you review?

**Comment by elexis1** [comment]
/ 2 \* 2 seems bad as its some random number, not the actual one.
Committed this one: http://trac.wildfiregames.com/changeset/18548

**Comment by elexis1** [comment]
also notice that files should end with a newline, so the second hunk was not needed
