### ISSUE TITLE
RMgen2 Proposal

### ISSUE THREAD

**Issue by ghost** [0ADMods/maps_random_by_kali#27]
@elexis1 For me, RMgen1 is really complicated to read, lots of tiny variable names like fx and ix and requires a lot of copy/paste for basic features. RMgen2 made it really easy for me to create a bunch of basic maps, but it's not really equipped to do more complicated things. So, I've started kicking around some ideas here: https://github.com/0ADMods/maps_random_by_kali/wiki/RMGen2-Proposal

Would love to get your feedback and ideas so when we do improve it, it's working towards something everyone likes and can live with for a while.

**Comment by StanleySweet** [comment]
If you haven't already you can check FeXoR's comment on it here kahttp://irclogs.wildfiregames.com/2016-08-21-QuakeNet-%230ad-dev.log
