### ISSUE TITLE
Bunch of possible improvements (+ a bit of feedback on the fly)

### ISSUE THREAD

**Issue by niektb** [0ADMods/maps_random_by_kali#29]
To start, as far as applicable I tried to improve some Environmental settings and texture choices in a recent commit.
1. I'm not so fond of Ngorongoro. The texture transitions are really sharp and the terrain is somewhat unnatural IMHO.
2. Rouen is not really special, but it's rivers have a nice and natural shape. The crossings should be marked more clearly though since it's somewhat hard to see them.
3. I like Howe Sound a lot, however the terrain has some interpolation errors at medium size. (which is visible in the shadows) Also some more snow diversity would be nice.
4. I don't really have comments on Bahrain and Marmara.

**Comment by elexis1** [comment]
The terrain of the maps isn't that special indeed. We don't have that many actors unfortunately. What makes these maps interesting is the authenticity of the terrain.

**Comment by elexis1** [comment]
About ngorongo, I don't think that they are that the textures transitions are that ugly, especially in comparison to dueling cliffs or many other new and old random map scripts.

Some things pointed out by others about that map on IRC in http://irclogs.wildfiregames.com/2016-09-04-QuakeNet-%230ad-dev.log

18:48 < erik_feneur> elexis: Not sure what you want me to comment on, buyt I'll try anyway =) Overall looks nice, looks like it's both visually interesting and reasonably balanced as far as I can tell from the image. The depression at a third from the left/about halfway down looks a bit weird/steep edges.
18:48 < erik_feneur> Not sure that area is either visually interesting enough or usable to warrant including.
18:53 < Yves`> elexis: it looks interesting and also playable. Having it as a circular map would be better. Something about the lighting looks a bit boring, but maybe it's just that the screenshot wasn't made with shadows and other graphical features enabled.
19:24 < fatherbushido> Ah, is ngorongo in the geographic area of our game ?
19:24 < fatherbushido> (i wondered the same with amazon)
19:26 < fatherbushido> (imo sahel must be the south limit)
