### ISSUE TITLE
Island Stronghold - some warning

### ISSUE THREAD

**Issue by elexis1** [0ADMods/maps_random_by_kali#4]
WARNING: SimpleObject: minDistance should be less than or equal to maxDistance

with these settings:
start {
    "settings": {
        "PlayerData": [{
            "Name": "You",
            "Civ": "maur",
            "Color": {
                "r": 46,
                "g": 46,
                "b": 200
            },
            "AI": "",
            "AIDiff": 3,
            "Team": -1
        }],
        "Seed": 24146,
        "CheatsEnabled": true,
        "AISeed": 26658,
        "CircularMap": true,
        "Size": 128,
        "GameType": "conquest",
        "VictoryScripts": ["scripts/TriggerHelper.js", "scripts/ConquestCommon.js", "scripts/Conquest.js"],
        "PopulationCap": 150,
        "Ceasefire": 0,
        "StartingResources": 300,
        "Name": "Island Strongholaaad",
        "Script": "island_stronghold.js",
        "Description": "Teams start off with nearly adjacent town centers on a small island, offering a fortified base from which to expand.",
        "BaseTerrain": ["medit_sand_wet"],
        "BaseHeight": -5,
        "Keywords": ["naval"],
        "Preview": "hyrcanian_shores.png",
        "XXXXXX": "Optionally define other things here, like we would for a scenario",
        "RatingEnabled": false,
        "TriggerScripts": ["scripts/TriggerHelper.js", "scripts/ConquestCommon.js", "scripts/Conquest.js"],
        "mapType": "random"
    },
    "map": "maps/random/island_stronghold",
    "mapType": "random",
    "mapPath": "maps/random/",
    "mapFilter": "all",
    "matchID": "836F63A81B0B6722",
    "gameSpeed": 1,
    "script": "island_stronghold.js",
    "timestamp": "1453836323",
    "engine_version": "0.0.19",
    "mods": ["mod", "public"]
}

**Comment by niektb** [comment]
Are you sure your script is sane? I see for example that you have a different previews, a different name and such...

**Comment by elexis1** [comment]
This is the header of the replay file, I only changed the title of that map locally. Not sure why the playerData only contains one item, since I'm sure set many players (maybe only one assigned in the game).
