### ISSUE TITLE
Move shared code to a separate file

### ISSUE THREAD

**Issue by elexis1** [0ADMods/maps_random_by_kali#7]
Currently _kali's maps duplicate the same functions. They should be moved to a separate file.

**Comment by elexis1** [comment]
Thanks to _kali for moving the shared functions to two files setup.js and gaia.js.

Notice that the current code doesn't work if its outside of the file.

This is because when setup.js is loaded (RMS.LoadLibrary("rmgen");), some variables are initialized immediately, with getSettings trying to access g_Map:
const m = getSettings(randInt(1, 8));
const t = constTerrains();
const g = constGaia();
const p = constProps();
const tc = constTileClasses();
const f = constForests();

But g_Map is initialized only after InitMap();

In order to fix this issue, the initialization of these values must be done in a function and that function called after InitMap().

Also having variable names with only one letter is terrible, especially if those are globals used in multiple files. It should be g_Foo.

**Comment by elexis1** [comment]
And whats that about in gaia.js, a copy&paste randomizePlacerCoordinates2 with
// for some reason, couldn't call the original RMgen function

This has to be solved too

**Comment by elexis1** [comment]
The dirt placement in addBluffs() also seems to be duplicated, why do we place dirt patches both before and after placing mountains? Wouldn't it be sufficient to place themafter the mountains?

**Comment by niektb** [comment]
@elexis1 Can't you create a custom library folder? (just like 'rmgen' is one) Or is that not wanted?

**Comment by elexis1** [comment]
Yes, must be moved to rmgen

**Comment by elexis1** [comment]
The 500 lines randomizeBiome duplicate can be removed from github, as the setBiome function was committed to svn :)

**Comment by ghost** [comment]
https://github.com/0ADMods/maps_random_by_kali/blob/master/maps/random/rmgen/gaia.js#L1100-L1162
was initially setup for debugging.  For some reason, createAreas didn't seem to be returning the array of coordinates from the terrain clump that was placed.  However, it might have been a bug in my code that was since fixed as the functions look identical to rmGen.  If we replace createAreas2 with createAreas, I don't see why it wouldn't still work.  The function is only used in "bluffs", so the easiest would be to test on "Ambush" which is guaranteed to have bluffs.  If the bluffs slope then it's all good.  If they look like plateaus then something broke.

**Comment by ghost** [comment]
EDIT: I think I can remove it.

The layered styling is a hack to prevent resources from showing up on impassable bluffs.  Basically, when a bluff is created it's assigned type "bluff".  That creates a plateau.  Then, the function slopes the plateau in one direction.  However, if during that process we find that it's not accessible, I let it still become a sloped bluff, but add a class of "mountain" to all points.  So, when we go to decorate it, if it's a "bluff" it gets decoration and resources.  If it's a "bluff" and a "mountain" it only gets decorated with unclickable entities.

**Comment by elexis1** [comment]
Why did you add the variable "players" back to Frontier? It seems to be an unused variable (only calling addBases itself seems relevant there)

**Comment by ghost** [comment]
I removed it now, and from the other maps where it's not being used
