### ISSUE TITLE
Assumption of 8 player maximum

### ISSUE THREAD

**Issue by elexis1** [0ADMods/maps_random_by_kali#8]
getTeams in setup.js loops to the number 9. But at some point we might increase the maximum player number, so the code must be more versatile (we had this issue for island stronghold too, so we can likely take code from there).

**Comment by ghost** [comment]
ok, is there a variable we could use instead?  maybe set a global const like MAX_PLAYERS in RMgen?

**Comment by ghost** [comment]
what's the best way to fix this or leave it as is?

**Comment by elexis1** [comment]
Why would we want that number 8 in there at all, it should only group the given teams, which can be done for an arbitrary amount of players and teams. Committed a fix (also mentioned before that island stronghold had a fix for that).
