### ISSUE TITLE
g_MapSettings variable already in use

### ISSUE THREAD

**Issue by ghost** [0ADMods/maps_random_by_kali#9]
Changing mapSettings to g_MapSettings here:
https://github.com/0ADMods/maps_random_by_kali/blob/master/maps/random/rmgen/setup.js#L1

breaks the maps.  apparently g_MapSettings is already in use in the library.  We could possibly get around it by not declaring it and attempting to add properties to it, or find a different name for it, whichever is easier.

**Comment by elexis1** [comment]
g_MapInfo.

Looks like the RMS library should also use only one function get all attributes instead of one for every attribute...
